[package]
name = "s3-slices"
version = "0.1.0"
authors = ["scnypl4sas <yunpeng.li@sas.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
